export const spots = [
  {
    name: "Hossegor - La Gravière",
    region: "Landes",
    country: "France",
    coords: [43.6656, -1.4436],
  },
  {
    name: "Hossegor - La Nord",
    region: "Landes",
    country: "France",
    coords: [43.6742, -1.4457],
  },
  {
    name: "Capbreton - Le Santocha",
    region: "Landes",
    country: "France",
    coords: [43.6429, -1.4498],
  },
  {
    name: "Seignosse - Les Estagnots",
    region: "Landes",
    country: "France",
    coords: [43.6921, -1.441],
  },
  {
    name: "Seignosse - Le Penon",
    region: "Landes",
    country: "France",
    coords: [43.6992, -1.4441],
  },
  {
    name: "Vieux-Boucau",
    region: "Landes",
    country: "France",
    coords: [43.7921, -1.4094],
  },
  {
    name: "Ondres",
    region: "Landes",
    country: "France",
    coords: [43.56, -1.4662],
  },
  {
    name: "Anglet - Les Cavaliers",
    region: "Pays basque",
    country: "France",
    coords: [43.523, -1.5368],
  },
  {
    name: "Biarritz - Côte des Basques",
    region: "Pays basque",
    country: "France",
    coords: [43.4835, -1.5656],
  },
  {
    name: "Guéthary - Parlementia",
    region: "Pays basque",
    country: "France",
    coords: [43.4221, -1.6097],
  },
  {
    name: "Saint-Jean-de-Luz - Lafitenia",
    region: "Pays basque",
    country: "France",
    coords: [43.4061, -1.6386],
  },
  {
    name: "Hendaye",
    region: "Pays basque",
    country: "France",
    coords: [43.37, -1.789],
  },
  {
    name: "Lacanau Central",
    region: "Gironde",
    country: "France",
    coords: [44.9774, -1.203],
  },
  {
    name: "Carcans Plage",
    region: "Gironde",
    country: "France",
    coords: [45.0862, -1.1325],
  },
  {
    name: "Hourtin",
    region: "Gironde",
    country: "France",
    coords: [45.2238, -1.1785],
  },
  {
    name: "Biscarrosse",
    region: "Landes",
    country: "France",
    coords: [44.4472, -1.2527],
  },
  {
    name: "Mimizan",
    region: "Landes",
    country: "France",
    coords: [44.2132, -1.3028],
  },
  {
    name: "Cap Ferret - Truc Vert",
    region: "Gironde",
    country: "France",
    coords: [44.7322, -1.2523],
  },
  {
    name: "La Torche",
    region: "Bretagne",
    country: "France",
    coords: [47.8198, -4.3588],
  },
  {
    name: "Crozon - La Palue",
    region: "Bretagne",
    country: "France",
    coords: [48.2606, -4.6148],
  },
];